workflows:
  build:
    name: Build and Test
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the project
        script: |
          npm run build
      - name: Run tests
        script: |
          npm test
    environment:
      NODE_ENV: production
